export const toRotate = [
  "Quiero una camioneta jeep 2017",
  "Necesito un coche pequeño para el trabajo",
  "Estoy buscando un Jetta que sea eficiente en gasolina",
  "Busco una SUV espaciosa para la familia",
  "Deseo comprar un coche deportivo de segunda mano",
  "¿Cuáles son los mejores modelos de autos eléctricos?",
  "Estoy interesado en un sedán de lujo",
  "¿Dónde puedo encontrar una camioneta pickup en oferta?",
  "Quiero un coche con sistema de navegación integrado",
  "Busco un hatchback con buena eficiencia de combustible",
  "¿Hay alguna oferta de leasing para un SUV híbrido?",
  "Necesito un coche con tracción en las cuatro ruedas",
  "¿Cuál es el precio promedio de un coche compacto?",
  "Busco un vehículo familiar con asientos plegables",
  "Quiero un combi naranja para viajes de aventura",
  "Coche rojo eléctrico",
  "Busco un SUV con tercera fila de asientos",
  "Necesito un coche con gran capacidad de carga",
  "¿Dónde puedo encontrar un descapotable a buen precio?",
  "Estoy interesado en un coche con tecnología híbrida",
  "¿Cuál es el SUV más seguro del mercado?",
  "Busco un coche compacto con bajo consumo de combustible",
  "Quiero un coche familiar con puertas corredizas",
  "¿Hay alguna oferta de financiamiento para un coche nuevo?",
  "Necesito un todoterreno para aventuras off-road",
  "Coche rojo deportivo",
  "SUV espaciosa",
  "Coche pequeño eficiente",
  "Camioneta pickup oferta",
  "Hatchback eficiencia combustible",
  "Oferta leasing SUV híbrido",
  "Coche tracción cuatro ruedas",
  "Coche compacto precio promedio",
  "Vehículo familiar asientos plegables",
  "Combi naranja viajes aventura",
  "Coche blanco elegante",
  "SUV potente y versátil",
  "Coche económico de alta calidad",
  "Camioneta pickup todo-terreno",
  "Descapotable deportivo y elegante",
  "Sedán compacto y eficiente",
  "Coche familiar seguro y cómodo",
  "Hatchback ágil y divertido de conducir",
  "SUV híbrido con bajo consumo de combustible",
  "Coche deportivo de lujo",
  "Camioneta espaciosa con capacidad de remolque",
];