import { test, expect } from '@playwright/test'
import { timeout } from '../../playwright.config'


test('test', async ({ page }) => {
    await page.goto('http://localhost:3000/');
    await page.getByRole('link', { name: 'Acura' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Alfa Romeo' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Audi' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Baic' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Bmw' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Buick' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Cadillac' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Chevrolet' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Chrysler' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Dodge' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Fiat' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('link', { name: 'Ford' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Gmc' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Honda' }).click();
    await page.goto('http://localhost:3000/');
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Hyundai' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Infiniti' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Jac' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Jaguar' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Jeep' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Kia' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Land Rover' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Lincoln' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Mazda' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('link', { name: 'Mercedes Benz' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Mg' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Mini' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 2' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Mitsubishi' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Nissan' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Peugeot' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Porsche' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Renault' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Seat' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Smart' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Suzuki' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Toyota' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('link', { name: 'Volkswagen' }).click();
    await page.getByRole('link', { name: 'Logo' }).click();
    await page.getByRole('button', { name: 'Go to page 4' }).click();
    await page.getByRole('button', { name: 'Go to page 3' }).click();
    await page.getByRole('button', { name: 'Go to page 4' }).click();
    await page.getByRole('link', { name: 'Volvo' }).click();
  });